name: CI/CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: aymen
          POSTGRES_PASSWORD: aymen
          POSTGRES_DB: prem_stats
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U aymen"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Verify Maven Build
        run: mvn clean verify -DskipTests=false

      - name: Run JUnit Tests
        run: mvn test

      - name: Build the Application
        run: mvn package -DskipTests=true

      - name: Run Application
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/prem_stats
          SPRING_DATASOURCE_USERNAME: aymen
          SPRING_DATASOURCE_PASSWORD: aymen
        run: java -jar target/*.jar

